configuration:
- Debug

build_script:
# Restore all
- dotnet restore Linq.Search.Core\Linq.Search.Core.csproj
- dotnet restore Linq.Search.Core.Tests\Linq.Search.Core.Tests.csproj

# Build Code
- dotnet build Linq.Search.Core\Linq.Search.Core.csproj -c %CONFIGURATION% --framework netstandard2.0

# Build Tests
- dotnet build Linq.Search.Core.Tests\Linq.Search.Core.Tests.csproj -c %CONFIGURATION%

test_script:
# Run tests for EntityFramework.DynamicLinq
- dotnet test -c %CONFIGURATION% --no-build Linq.Search.Core.Tests\Linq.Search.Core.Tests.csproj

after_test:
# Use System.Linq.Search.Core.Tests as coverage tests
  - nuget.exe install OpenCover -ExcludeVersion
  - pip install codecov

  - cmd: '"OpenCover\tools\OpenCover.Console.exe" -target:dotnet.exe -targetargs:"test Linq.Search.Core.Tests\Linq.Search.Core.Tests.csproj --configuration %CONFIGURATION% --framework netcoreapp2.0 --no-build" -output:coverage.xml -register:user -filter:"+[System.Linq.Dynamic.Core]* -[*Tests*]*" -nodefaultfilters -returntargetcode -oldstyle'
  - codecov -f "coverage.xml"