before_build:
 - nuget restore
build_script:
 - msbuild /verbosity:quiet "Linq.Search.Core"
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"Linq.Search.Core.Tests\bin\Debug\netcoreapp2.0\Linq.Search.Core.Tests.dll -noshadow" -output:"coverage.xml" -filter:"+[Linq.Search.Core*]* -[Linq.Search.Core.Tests*]*"
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml"